CREATE DATABASE TravelCompanion 
GO 

USE TravelCompanion
GO

CREATE TABLE ShareContent
(
  Id           UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Slogan       NVARCHAR(MAX),
  Introduction NVARCHAR(MAX),
  Email        NVARCHAR(35),
  Phone        VARCHAR(11),
  Address      NVARCHAR(500)
)
GO

CREATE TABLE Account
(
  Id       UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Email    NVARCHAR(35),
  Username NVARCHAR(50),
  Password VARCHAR(50),
  Bio      NVARCHAR(MAX),
  Avatar   NVARCHAR(MAX),
  Status   INT
)
GO

CREATE TABLE Blog
(
  Id           UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Title        NVARCHAR(1000),
  Description  NVARCHAR(MAX),
  Content      NTEXT,
  DateCreated  DATETIME,
  DateModified DATETIME,
  Status       INT
)
GO 

CREATE TABLE Category
(
  Id   UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Name NVARCHAR(100)
)
GO

CREATE TABLE Ward
(
  Id          UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Name        NVARCHAR(500),
  Description NVARCHAR(MAX),
  Content     NTEXT
)
GO

CREATE TABLE Place
(
  Id         UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Name       NVARCHAR(1000),
  Address    NVARCHAR(500),
  OpenTime   DATETIME,
  CloseTime  DATETIME,
  Price      FLOAT,
  CategoryId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Category(Id),
  WardId     UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Ward(Id)
)
GO 

CREATE TABLE BlogImage
(
  Id      UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  ImgLink NVARCHAR(MAX),
  BlogId  UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Blog(Id)
)
GO

CREATE TABLE PlaceImage
(
  Id      UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Imglink NVARCHAR(MAX),
  PlaceId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Place(Id)
)
GO